### ISSUE TITLE
Multiple Java applets on a single page not supported 

### ISSUE THREAD

**Issue by sderossi** [leaningtech/cheerpj-appletrunner#1]
When multiple Java applets are embedded within a page, only the first gets converted and replaced with JavaScript.

Example: <https://www.cis.upenn.edu/~matuszek/General/JavaVersionTests/JavaTests.html>

**Comment by alexp-sssup** [comment]
Another example:  http://cmup.fc.up.pt/cmup/relatividade/RR/node3.html

**Comment by alexp-sssup** [comment]
Supported with CheerpJ Applet Runner 4.7
