### ISSUE TITLE
This applet does not work well.

### ISSUE THREAD

**Issue by hurumori** [leaningtech/cheerpj-appletrunner#10]
Thank you very much for making great tools!
This applet does not work well.

https://pbbs.sakura.ne.jp/cgi/poti/
[neo] uncheck > paint

![180930-152847](https://user-images.githubusercontent.com/43722233/46257199-efd97080-c4f0-11e8-9658-50016ec483cf.jpg)

![180930-153124](https://user-images.githubusercontent.com/43722233/46257212-04b60400-c4f1-11e8-92d5-b679711b250d.jpg)
 
01. Occasionally, when the cursor moves out of the canvas, the line drawn next will be broken.
![test](https://user-images.githubusercontent.com/43722233/46257216-1b5c5b00-c4f1-11e8-8b2b-1d5357bf2bfd.jpg)

02. Font tool Window : toolbar >  color(drag the mouse) > font
     Font choices are very few.(It does not seem to show the fonts installed on windows)
![180930-144748](https://user-images.githubusercontent.com/43722233/46257234-51014400-c4f1-11e8-8ad3-9df8b1a202c3.jpg)

03. Font tool : Font tool Window > [Apply] > click on canvas
     After typing the characters in the textarea, there is no reaction even if I press the enter key, can not be determined.
![180930-164209](https://user-images.githubusercontent.com/43722233/46257250-827a0f80-c4f1-11e8-8391-e3809deb0973.jpg)

04. Layer Window : toolbar > click on "layer0" > Hold the left mouse button down and drag [layer(n)]
　　I can not change the order of layers.
![180930-163432](https://user-images.githubusercontent.com/43722233/46257253-8c037780-c4f1-11e8-9be0-3ad34ca2e9b1.jpg)

05. Layer Window : click the mouse button on the [menu].
    I can not open the layer menu.
![180930-163907](https://user-images.githubusercontent.com/43722233/46257269-d1c04000-c4f1-11e8-8bd4-72452c1afb61.jpg)

Applet is
https://hp.vector.co.jp/authors/VA016309/spainter/file/sptr_all1114.zip

My PC environment
Windows7(x64) + Chrome 69.0.3497.100

Do you have any solutions? 
Thank you for reading.

**Comment by alexp-sssup** [comment]
Thanks for reporting these problems. We need some time to take a look at the various issues, as they are all separate problems.

Issue number 2 (lack of installed fonts) is expected. CheerpJ completely runs inside the browser and cannot access the fonts installed on the system.

**Comment by hurumori** [comment]
Thank you very mach for your response!

I am sorry.
Although one more,
An applet of the same creator as the above applet runs out of control under certain conditions (loading pch file).

http://my.reset.jp/~cur/t/oekaki.html

The *.pch file is the animation for the drawing.
By reading the pch file to the applet, I can draw from the continuation from the picture of the state with no deterioration.

drawing >> send cgi >> *.jpg or *.png + *.pch

ex.　http://www.nofna.com/pch/

Waterfox & jre8u181 (+pch) 
![181006-164210](https://user-images.githubusercontent.com/43722233/46569036-1a607900-c98a-11e8-9ed5-7a661fbcf0f6.jpg)

Chrome 69 (+pch)
![181006-164553](https://user-images.githubusercontent.com/43722233/46571996-ca99a600-c9b9-11e8-8824-65f27516fadb.jpg)

Chrome69 (default)
![181006-224934](https://user-images.githubusercontent.com/43722233/46572032-60353580-c9ba-11e8-9328-602242e1d4c4.jpg)

original applet
https://hp.vector.co.jp/authors/VA016309/paintbbs/file/pbbs222_8.zip

my pch file
http://my.reset.jp/~cur/t/rep_2211.pch

chrome network log
[www.google.co.jp-1538810775184.log](https://github.com/leaningtech/cheerpj-appletrunner/files/2452823/www.google.co.jp-1538810775184.log)

![181006-164553 2](https://user-images.githubusercontent.com/43722233/46569026-fd2baa80-c989-11e8-948c-a4e5ea40ce45.jpg)

Any help would be appreciated.
Thank you for reading.

**Comment by alexp-sssup** [comment]
These bugs should be all fixed with CheerpJ Applet Runner version 5.1. Please update the extension and try again. If CheerpJ Applet Runner is working well for you we would really appreciate a 5-star review here: https://chrome.google.com/webstore/detail/cheerpj-applet-runner/bbmolahhldcbngedljfadjlognfaaein

**Comment by hurumori** [comment]
I appreciate your kindness.
Thank you so much! :)
