### ISSUE TITLE
Not working on this site

### ISSUE THREAD

**Issue by agunslinger** [leaningtech/cheerpj-appletrunner#12]
http://www.jgiesen.de/SunCompassCole/index.html   Just FYI

**Comment by alexp-sssup** [comment]
Fixed in CheerpJ Applet Runner version 6.4.

If our extension is working for you, we would really appreciate if could leave a 5-star review for us here: https://chrome.google.com/webstore/detail/cheerpj-applet-runner/bbmolahhldcbngedljfadjlognfaaein
