### ISSUE TITLE
Not working educational content

### ISSUE THREAD

**Issue by hagenaue** [leaningtech/cheerpj-appletrunner#13]
Browser information: Chrome Version 70.0.3538.110 (Official Build) (64-bit)
Operating system:  MacOS 10.12.6

I spent the past two hours using CheerPJ Applet Runner to open Java on the website onlinestatbook.com.  It was working for some of the Java simulations, and was buggy for others. I was still thrilled with the .app - having access to at least some of the textbook simulations is better than nothing!

... and then it stopped working for all of them (including the ones that it had worked for an hour ago).

When I navigate back to sites where CheerPJ had worked this morning it shows a grey icon ("no applet found or permissions required") and the website is again providing the "Java must be enabled to run this simulation" error message. The CheerPJ button also does not have an option for "run applets" any more, only "disable" (?). If I disable the applet and then run it again, it still doesn't work. 

Here's an example of some of the websites that worked this morning but do not work now:
http://onlinestatbook.com/2/introduction/sampling_demo.html
http://onlinestatbook.com/2/summarizing_distributions/variance_est.html
http://onlinestatbook.com/2/probability/conditional_demo.html
http://onlinestatbook.com/2/describing_bivariate_data/pearson_demo.html
http://onlinestatbook.com/2/describing_bivariate_data/restriction_demo.html
http://onlinestatbook.com/2/tests_of_means/robust_sim.html

I tried clearing my Browsing Data and that didn't help. I also double checked my preferences in Chrome to make sure that JavaScript was allowed, as well as pop-ups and redirects from onlinestatbook.com.

Any thoughts?  Thanks!

**Comment by alexp-sssup** [comment]
Please make sure that the version of the applet is 6.2, there was a mistake in the package for 6.1.

**Comment by hagenaue** [comment]
Ooooh interesting - the version on the Chrome Store is 5.1: https://chrome.google.com/webstore/detail/cheerpj-applet-runner/bbmolahhldcbngedljfadjlognfaaein?hl=en

**Comment by hagenaue** [comment]
... but now it just changed to v 6.2?

**Comment by alexp-sssup** [comment]
The quickest way to update is to go to chrome://extensions/, enable "Developer mode" and click "Update". You can disable "Developer mode" afterwards. In Dev mode you can also easily see what version you have.

**Comment by hagenaue** [comment]
Thanks! After updating, it looks like the Java simulations on those websites are viewable again. Hurray! :)

Next question:  Is there any chance that CheerPJ Applet Runner will ever be able to make some of the other Java simulations within this textbook viewable again?  I believe they were written a long time ago (Java 1.1?) and I'm not sure that they will ever be updated (PhDWare), but they are incredibly helpful teaching tools.  

Here's the links for a few of them as examples:
http://onlinestatbook.com/2/introduction/measurement_demo.html
http://onlinestatbook.com/2/probability/birthday_demo.html
http://onlinestatbook.com/2/tests_of_means/t_distribution_demo.html

**Comment by alexp-sssup** [comment]
Yes, they will most  probably run eventually. Most probably the issues are minor but we will to allocate development time to them and I am not able to tell you now how soon they will be fixed. If our extension is helpful for you we would really appreciate if you could us a 5-start review here: https://chrome.google.com/webstore/detail/cheerpj-applet-runner/bbmolahhldcbngedljfadjlognfaaein

**Comment by alexp-sssup** [comment]
Thank you, let's keep this issue open to track the fixes for the pages that do not work.

**Comment by alexp-sssup** [comment]
We are currently trying to get a better idea of what is not working exactly. It seems to us that all simulations can be loaded, although some of them do not render perfectly. Is this also true for you or some of them actually do not load?

**Comment by alexp-sssup** [comment]
To the best of our understading these applets work when using the just released CheerpJ Applet Runner version 6.3
