### ISSUE TITLE
Threads do not yield or there is no Swing thread

### ISSUE THREAD

**Issue by jburse** [leaningtech/cheerpj-appletrunner#14]
Dear Leaningtech,

I am having problems with porting an applet to the Cheerpj. Somehow
everything works fine, except for a small issue that the menus get 
blocked when my application is running, although its running in a
separate thread. Is this something by design or an error?

Already the thread states look strange, I get in the normal applet viewer
from JDK-8 and this is what I expect (one thread is waiting):

![image](https://user-images.githubusercontent.com/5411487/50048377-91249b80-00ca-11e9-8764-6768668985b5.png)

**Comment by jburse** [comment]
On the other hand cheerpj shows me the following result (I don't see
some thread waiting, Thread.getState().name()):

![image](https://user-images.githubusercontent.com/5411487/50048381-b44f4b00-00ca-11e9-9823-2e26241b51b0.png)

**Comment by jburse** [comment]
The consequences are far fetching in as far, I cannot interrupt my application
anymore. Normally I can use the menus via the Swing thread, and then I
can kill Thread-2 or Thread-3. Here is an example, I simply use the abort
menu of my applicaton:

![image](https://user-images.githubusercontent.com/5411487/50048393-2c1d7580-00cb-11e9-9d42-ebba726f89fb.png)

This will set a flag in the thread and the interpreter will bail out:

![image](https://user-images.githubusercontent.com/5411487/50048402-52431580-00cb-11e9-88a6-30968e967b04.png)

**Comment by jburse** [comment]
With Cheerpj this aint working anymore. Somehow I cannot use
the menus when a thread is busy:

![image](https://user-images.githubusercontent.com/5411487/50048417-ae0d9e80-00cb-11e9-99d6-8f9645201caf.png)

And then some Chrome Watchdog comes up, and basically destroys my app:

![image](https://user-images.githubusercontent.com/5411487/50048420-c54c8c00-00cb-11e9-83f7-98e130743843.png)

**Comment by jburse** [comment]
I have no clue what heuristics the Watchdog is using to decide that my application
is blocked, because it has only a separate thread running, but if there were a Swing thread
as is the case in the JDK appletviewer, the application would respond.

I have some suspicion what causes the problem. If there is no Swing thread,
it could be Swing thread time is stolen from other thread whenever they yield,
like in a wait. But unfortunately my application threads do not automatically

when they are running. The interrupt flag is polled via volatile variable.
If I knew that my threads need to yield somehow, I could add such yield
instractions to the polling step, making the application possibly work

on cheerpj as well.

**Comment by alexp-sssup** [comment]
I did not have a chance to analyse the actual applet, but in general in the browser there is only 1 thread. Moreover there is no way to preempt the thread to run other code. This means that a thread that does something like ```while(1) { }``` in Java can effectively lock the application.

Ignore the reported thread states, they are not synchronized with the actual internal state (that is a bug).

**Comment by alexp-sssup** [comment]
To clarify, CheerpJ supports multiple Java threads, but they are emulated on top of the single thread that the browser provides. WebWorkers are not equivalent to threads and can't be used to provide this functionality.

**Comment by jburse** [comment]
Thank you for your quick response, even during christmas time. 
I could call Thread.yield() in my while(1) { } loop, would this maybe help?

**Comment by alexp-sssup** [comment]
That would definitely help

**Comment by jburse** [comment]
There are mixed results now. The while(1) {} loop, I was called Thread.yield() every 10'000 now. Will probably experiment whats the best number here. So I can indeed now kill an infinite loop:
