### ISSUE TITLE
About getting a thread stack trace

### ISSUE THREAD

**Issue by jburse** [leaningtech/cheerpj-appletrunner#15]
To debug https://github.com/leaningtech/cheerpj-appletrunner/issues/14 I am trying to retrieve a stack trace of a thread. I am using Thread.getStackTrace() for this purpose. This works fine on my side:

![image](https://user-images.githubusercontent.com/5411487/50053015-ecd44080-012d-11e9-9610-722e29383543.png)

**Comment by jburse** [comment]
Is there any recommendation to inspect stack traces of threads in CheerpJ? I would like to check whether the thread is as expected in a Object.wait() or does something else.

**Comment by alexp-sssup** [comment]
```Thread.getStackTrace``` is not supported yet (that is a bug). But you should be able to use ```Throwable.getStackTrace``` from an existing exception.

**Comment by jburse** [comment]
Thank you for your quick response, even during christmas time. Got it!

**Comment by alexp-sssup** [comment]
This should be fixed in CheerpJ Applet Runner version 6.6
