### ISSUE TITLE
About blocking show() resp. setVisible(true)

### ISSUE THREAD

**Issue by jburse** [leaningtech/cheerpj-appletrunner#16]
Dear Leaningtech,

I am trying to port an applet to CheerpJ. This applet uses JApplet from Swing, and also opens JDialog from with the applet. It seems there is a discrepancy between the original Swing implementation of modal dialogs and the CheerpJ implementation of modal dialogs. We use the following code:

    void showDialog(InterfaceHolder f) {
        setEnvironment(f.getEnvironment());
        pack();
        setLocationRelativeTo((Component) f);
        setVisible(true);
        setEnvironment(null);
    }

Usually the original Swing implementation blocks during setVisible(true) or show(). This is specified in the show() documentation as follows:

> If the dialog is modal and is not already visible, this call
> will not return until the dialog is hidden by calling hide or
> dispose. It is permissible to show modal dialogs from the event
> dispatching thread because the toolkit will ensure that another
> event pump runs while the one which invoked this method is blocked.

https://docs.oracle.com/javase/7/docs/api/java/awt/Dialog.html#show%28%29

**Comment by jburse** [comment]
Unfortunately CheerpJ does not block. I figured this out by tracing the setEnvironment() calls. The devtools console shows me that there is no blocking:

![unbenannt](https://user-images.githubusercontent.com/5411487/50057912-54f84600-0171-11e9-95d5-047b0aa3cdc8.PNG)

Is there a way to have a blocking setVisible(true) or show() in CheerpJ, so that I don't need to completely rewrite the application?

**Comment by jburse** [comment]
The good news is, the problem seems not to persis to JOptionPane.showInputDialog and JOptionPane.showMessageDialog. At least I don't see some abnormal behaviour in my application. For example a little InputDialog is modal in that I cannot use the applet menu bar:

**Comment by jburse** [comment]
On the other hand here is a side effect of the missing blocking of setVisible(true) resp. show(). Since the applet menu bar can be accessed, I can open multiple modal dialogs:

![multi_dialogs](https://user-images.githubusercontent.com/5411487/50058239-af93a100-0175-11e9-97f7-e4ce467d60d6.gif)

**Comment by jburse** [comment]
In case somebody from Leaningtech would like to reproduce the test, here is a link to the applet:

http://www.jekejeke.ch/asterix/page.html

The involved archive interpreter.jar has anyway a distribution license.

**Comment by alexp-sssup** [comment]
```Dialog.show()``` should be properly blocking in CheerpJ Applet Runner version 6.6

**Comment by jburse** [comment]
This is great news!

I see Applet Runner 6.6 was out 3. January 2019.  
Will do some regression testing as soon as I have time.

**Comment by jburse** [comment]
Of course something headless is also planned. CheerpJ AOT 
compiler to generate jar.js would be helpful in this respect. 

The competitors are not sleeping:

Tau Prolog drives rules and queries for Klipse HTML5/JavaScript 
http://blog.klipse.tech/prolog/2019/01/01/blog-prolog.html

**Comment by jburse** [comment]
I could make some regression testing. It now partly works. The event
loop is indeed blocking, and my application logic translates from Swing
to CheerpJ. I can open this subwindow:

**Comment by jburse** [comment]
But I noticed that an other problem that persists. Namely that
the menu bar is still working, even when the dialog is modal.
I will open a separate issue for that.
