### ISSUE TITLE
About ManagementFactory

### ISSUE THREAD

**Issue by jburse** [leaningtech/cheerpj-appletrunner#19]
Dear Leaningtech,

Is java.lang.management.* supported? My code hangs in something like this:

            ThreadMXBean tb = ManagementFactory.getThreadMXBean();
            if (tb.isThreadCpuTimeEnabled()) {
                long cputime = tb.getCurrentThreadCpuTime() / 1000000L;
                return TermAtomic.normBigInteger(cputime);
            } else {
                return null;
            }

**Comment by jburse** [comment]
This one gets me into the debugger:

**Comment by alexp-sssup** [comment]
The management interface is only partially supported as not all the required statistics are available in the browser. CheerpJ Applet Runner 6.6 should not trigger a debugger statement anymore.

**Comment by jburse** [comment]
Thank you very much, I see Applet Runner 6.6 was out 3. January 2019.  
Will do some regression testing as soon as I have time.
