### ISSUE TITLE
alt characters do not work on MacOS platform

### ISSUE THREAD

**Issue by jburse** [leaningtech/cheerpj-appletrunner#21]
Dear Leaningtech,

This could be a known issue. I just tried the applet runner on the MacOS platform and there seems to be an issue with the keyboard. The usual characters work. But those reachable via the alt modification keys do not show up in the applet runner inside a JTextComponent:

![bildschirmfoto 2018-12-17 um 21 43 27](https://user-images.githubusercontent.com/5411487/50114636-4c713f80-0245-11e9-8bd4-1bea6a5fcf94.png)

**Comment by alexp-sssup** [comment]
Fixed in CheerpJ Applet Runner 6.7

**Comment by jburse** [comment]
I could do regression testing. Works fine. Thank you!
