### ISSUE TITLE
I don't get InvocationTargetException when using reflection

### ISSUE THREAD

**Issue by jburse** [leaningtech/cheerpj-appletrunner#23]
This is related to another issue here https://github.com/leaningtech/cheerpj-appletrunner/issues/22 , which I recognized when analysing the problem. It seems that InvocationTargetException is not thrown by cheerpj. The test case I found is the following. Here is the expected result:

![expected](https://user-images.githubusercontent.com/5411487/50304746-145e3c80-0491-11e9-9606-db5a8185d887.gif)

But the cheerpj gives me something else:

![unbenannt](https://user-images.githubusercontent.com/5411487/50304759-2049fe80-0491-11e9-96a1-4a976b29cbe8.PNG)

**Comment by jburse** [comment]
I guess the NumberFormatException permeates without being wrapped
inside InvocationTargetException, and is then catched as an IllegalArgumentException
by my code. But IllegalArgumentException has a special semantics in
connection with reflection. This is my code that handles reflective calls:

    static Object invokeMethod(Method method, Object obj, Object[] args)
            throws EngineException, EngineMessage {
        try {
            return method.invoke(obj, args);
        } catch (InvocationTargetException y) {
            Throwable x = y.getCause();
         [...]
                throw Types.mapThrowable(x);
         [...]
        } catch (IllegalArgumentException x) {
            throw new EngineMessage(EngineMessage.permissionError(
                    AbstractFactory.OP_PERMISSION_APPLY,
                    AbstractFactory.OP_PERMISSION_METHOD,
                    SpecialForeign.methodToCallable(method.getName(),
                            method.getParameterTypes())));

See also:
https://github.com/jburse/jekejeke-devel/blob/master/jekrun/headless/jekpro/tools/foreign/AbstractMember.java#L214

I know this is tricky, and it took me some time to get all the corners of
Java reflection. But it is documented:

> IllegalArgumentException - if the method is an instance method and
> the specified object argument is not an instance of the class or 
> interface declaring the underlying method (or of a subclass or 
> implementor thereof); if the number of actual and formal parameters 
> differ; if an unwrapping conversion for primitive arguments fails; or if, 
> after possible unwrapping, a parameter value cannot be converted to 
> the corresponding formal parameter type by a method invocation conversion.

**Comment by jburse** [comment]
This still this doesn't explain why https://github.com/leaningtech/cheerpj-appletrunner/issues/22 hangs. Also I am not sure about a workaround here. At least the problem is not that aggravated, the good thing is that we get some exception!

**Comment by jburse** [comment]
To get some further evidence what my workaround should be, I was testing whether not only method.invoke(obj, args); doesn't throw InvocationTargetException, but whether constructor.newInstance(args); has the same problem.

**Comment by alexp-sssup** [comment]
This problem should be fixed in CheerpJ Applet Runner 6.8.

PS. Please consider upgrading to the AOT compiler for faster execution in general.

**Comment by jburse** [comment]
Hi,  yes I noticed, on the debugger console, that it tries
GET interpreter.jar.js. So I guess I could precompile it.

But I rather expect that it only affects the load time,
and less the execution time. But if you say otherwise

I will be happy to due some benchmarking in due time.

**Comment by jburse** [comment]
I could do some regression testing. Works fine. Thank you!
