### ISSUE TITLE
Comparing with negative infinity

### ISSUE THREAD

**Issue by jburse** [leaningtech/cheerpj-appletrunner#25]
I have a workaround, but just for the record, I noticed the following discrepancy. 
In ordinary Java I get the following result:

    double x=Math.log(0); /* gives -Infinity */
    double y=Math.log(0); /* gives -Infinity */
    System.out.println(x==y);
    --> true

On the other hand CheerpJ gives me:

    System.out.println(x==y);
    --> false

I guess this is standardized:

> 15.21.1 Numerical Equality Operators == and !=: "In particular, 
> there is one value representing positive infinity and one value 
> representing negative infinity; each compares equal only to itself, 
> and each compares unequal to all other values."

**Comment by alexp-sssup** [comment]
This problem should be fixed in CheerpJ Applet Runner 6.8.
