### ISSUE TITLE
f.createNewFile() and f.delete() not working for '/files/'

### ISSUE THREAD

**Issue by jburse** [leaningtech/cheerpj-appletrunner#28]
We were expecting that '/files/' accepts file and directory operations.
But they seem to only work partially. It seems that new FileOutputStream() does
created an entry, but createNewFile() doesn't.

Also directory listing list() works but delete() doesn't work. I was checking
the operations on the instances of the Java class java.io.File.

![unbenannt](https://user-images.githubusercontent.com/5411487/50425611-15b9ab80-087b-11e9-9a75-a94978d1ea1c.PNG)

**Comment by jburse** [comment]
We found another anomaly related to java.io.File. It seems that through reflection,
the field File.separatorChar is returned as the value 0. Here is what is expected:

Ordinary Java:

In CheerpJ:

This could be related to the issue  here:

**Comment by jburse** [comment]
On the other hand we could find a fix for the missing `f.createNewFile()`. We just use `new FileOutputStream()`, and it will also create files for us in thee file tree /files/. As a result we have Prolog settings for our Prolog interpreter immediately without further ado.

This is due to the system settings which are cleverly set by CheerpJ, and make everything work for us without further fixes. Settings can now be used in our Prolog interpreter applet. An example setting, that is stored in this file. is the command line history. Great job!

![unbenannt](https://user-images.githubusercontent.com/5411487/50483228-12453200-09eb-11e9-9338-177c4f3c3e5b.PNG)

**Comment by alexp-sssup** [comment]
```f.createNewFile()``` and the ```separatorChar``` issue should be fixed in CheerpJ Applet Runner 6.7. ```f.delete()``` is indeed not supported at this time.

**Comment by alexp-sssup** [comment]
File deletion is supported in CheerpJ Applet Runner 8.7
