### ISSUE TITLE
Some java.lang.Math fields give 0.0 when accessed reflectively

### ISSUE THREAD

**Issue by jburse** [leaningtech/cheerpj-appletrunner#30]
I did some regression testing for:
https://github.com/leaningtech/cheerpj-appletrunner/issues/24

I don't now how to reopen an issue. But I have a new issue, that
now fields return 0.0, while the shouldn't. Here is what happens
in the ordinary JVM:

![unbenannt](https://user-images.githubusercontent.com/5411487/51407078-3532b400-1b5b-11e9-95a9-f2da2b4eab12.PNG)

**Comment by jburse** [comment]
And this is what CheerpJ delivers, the Applet Runner Version 6.9
Updated January 11, 2019. The result is not anymore pi:

![unbenannt2](https://user-images.githubusercontent.com/5411487/51407245-9a86a500-1b5b-11e9-9888-aa86316c3cb9.PNG)

**Comment by alexp-sssup** [comment]
Fixed in CheerpJ Applet Runner 6.10
