### ISSUE TITLE
Modal dialogs shouldn't allow restacking

### ISSUE THREAD

**Issue by jburse** [leaningtech/cheerpj-appletrunner#31]
I applied the workaround from #29, now using setModal() instead
of setModalityType(). As a result I can now run a whole bunch of dialogs,
that were not possible before. For example I can now change the console

colors, which seems to work as this screenshot shows:

![unbenannt](https://user-images.githubusercontent.com/5411487/51427194-36b0ba80-1bf5-11e9-98af-fe94fe109824.PNG)

**Comment by jburse** [comment]
But there is a small residual issue. Some of my modal dialogs have
sub modal dialogs. So the modal dialog opens itself a little modal dialog.
Here is an example:

![unbenannt2](https://user-images.githubusercontent.com/5411487/51427207-6e1f6700-1bf5-11e9-8a34-914f3f057643.PNG)

**Comment by alexp-sssup** [comment]
Restacking of windows blocked by modal dialogs is not possible anymore in CheerpJAppletRunner 7.0

**Comment by jburse** [comment]
Thank you for the notification. I will be happy to do 
some regression testing during february month.
