### ISSUE TITLE
Question about support of locks

### ISSUE THREAD

**Issue by jburse** [leaningtech/cheerpj-appletrunner#32]
Dear Leaningtech,

I am currently migrating my applet from home grown 
monitor based locks, which I could use as a fallback, to 

     ReentrantReadWriteLock, @Since 1.5
     https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/locks/ReentrantReadWriteLock.html

Does the CheerpJ runtime also support these concurrency
primitives. Are there some known limitations?

Best Regards

**Comment by alexp-sssup** [comment]
All the concurrency primitives are supported, there are no known limitations. Bugs could still be present. Honestly I expect ReentrantReadWriteLock to work.

**Comment by jburse** [comment]
Ok, I will soon give it a try. Thanks!
