### ISSUE TITLE
20190504 does not work properly

### ISSUE THREAD

**Issue by satopian** [leaningtech/cheerpj-appletrunner#33]
Thank you very much for making great tools!
This applet does not work well.

https://pbbs.sakura.ne.jp/cgi/poti/
[neo] uncheck > paint

![Screen-2019-05-12_15-45-44](https://user-images.githubusercontent.com/44894014/57578868-d3fa6c00-74ce-11e9-8817-7b2ce36a1d8a.jpg)

When you select a color on the right palette, the text on the tool bar disappears.
https://cjrtnc.leaningtech.com/20190424/loader.js
The text on the tool bar does not disappear.
Works fine.
https://cjrtnc.leaningtech.com/20190504/loader.js
The tool bar text disappears.
It does not work.

![190512_001](https://user-images.githubusercontent.com/44894014/57578873-dd83d400-74ce-11e9-89cc-57c5ccd27840.png)

**Comment by alexp-sssup** [comment]
Can you try if the https://cjrtnc.leaningtech.com/20190510_2/loader.js works instead?

**Comment by satopian** [comment]
https://cjrtnc.leaningtech.com/20190510_2/loader.js
![Screen-2019-05-12_18-53-50](https://user-images.githubusercontent.com/44894014/57580676-83dbd380-74e7-11e9-88ed-9dcabbda72c0.jpg)
It is an image of the test result.
It did not improve.

**Comment by alexp-sssup** [comment]
We will to take a look at the problem. But https://pbbs.sakura.ne.jp/cgi/poti/ gives a ```403 Forbidden``` code. It is expected.

**Comment by satopian** [comment]
このURLではどうでしょうか？
https://pbbs.sakura.ne.jp/test/

**Comment by alexp-sssup** [comment]
This other URL works, but it uses by default the old 20190424, which does not show the problem

**Comment by satopian** [comment]
The default settings have been rewritten.
https://cjrtnc.leaningtech.com/20190510_2/loader.js
Google Chrome Extension
https://chrome.google.com/webstore/detail/cheerpj-applet-runner/bbmolahhldcbngngljfadjlognfaaein/
Then,
https://cjrtnc.leaningtech.com/20190504/loader.js
Will work.
This applet is installed on many websites.
For example
http://neo.websozai.jp/
Here we use Chrome extensions.
![Screen-2019-05-12_19-47-14](https://user-images.githubusercontent.com/44894014/57581613-cfe14500-74f4-11e9-93a3-fd830c08a3d4.jpg)

**Comment by alexp-sssup** [comment]
It would be much easier for us to debug the problem if we could use the applet runner. Is there a page that we can access which is not integrated with a specific version?

**Comment by alexp-sssup** [comment]
Please ignore the previous comment, we can use http://neo.websozai.jp/. Apologies.

**Comment by satopian** [comment]
Test page too
I changed the setting to not specify the version.
https://pbbs.sakura.ne.jp/test/

**Comment by alexp-sssup** [comment]
Is the problem fixed with https://cjrtnc.leaningtech.com/20190512/loader.js

**Comment by satopian** [comment]
Thank you for your prompt response.
The problem is solved.

**Comment by alexp-sssup** [comment]
Great. The new update is currently been released as CheerpJ Applet Runner 7.8
