### ISSUE TITLE
The new version will not work.

### ISSUE THREAD

**Issue by satopian** [leaningtech/cheerpj-appletrunner#38]
Thank you for a useful app. However, the new version will not work.
The following URL is displayed in the browser.
<script src="https://127.0.0.1:8090/loader.js"></script>
localhost?

**Comment by alexp-sssup** [comment]
Yes, we made a mistake in the last released version of CheerpJ Applet Runner, we have already published a new fixed version but unfortunately Google takes several days to process the updates. We hope that today or tomorrow the problem will be fixed.

**Comment by satopian** [comment]
Updated to 2.0.
The problem has been resolved.
Thank you.
