### ISSUE TITLE
It doesnt work with runescape

### ISSUE THREAD

**Issue by dayoshiguy** [leaningtech/cheerpj-appletrunner#39]
I read the faq after writing this but the only reason you would ever need java is for runescape.

**Comment by alexp-sssup** [comment]
As documented in the FAQs, Runescape require custom networking access which is not possible out-of-the-box in modern browser. We have several ideas on how this problem could be solved, but it would be a complex project that we can only undertake if there is commercial interest from either Runescape itself or other projects requiring custom non-HTTP networking. I would like to recommend to report the issue to Runescape itself.
