### ISSUE TITLE
Right mouse click not working

### ISSUE THREAD

**Issue by GriskevicV** [leaningtech/cheerpj-appletrunner#44]
Right mouse click is not working.

**Comment by marsicplusplus** [comment]
Hi @GriskevicV,

What runtime are you using?
Could you provide us with a minimal testcase?

**Comment by GriskevicV** [comment]
Hi,
Unfortunately can't share much as this is financial system.
Built on old Oracle Forms version.
Valdemar

**Comment by marsicplusplus** [comment]
We offer free support only for applets available on the public internet.
If you need further assistance please send an email to: info@leaningtech.com
