### ISSUE TITLE
"shi-painter" does not start.

### ISSUE THREAD

**Issue by satopian** [leaningtech/cheerpj-appletrunner#46]
Bulletin board URL where the applet does not start
https://pbbs.sakura.ne.jp/cgi/neosample/poti-board-en/
"shi-painter" does not start.
![image](https://user-images.githubusercontent.com/44894014/120812445-f06f1280-c587-11eb-9053-5c6c6406a367.png)

"https://cjrtnc.leaningtech.com/latest/loader.js"
The applet does not start.
The start logo keeps spinning.
It used to work, but now it doesn't.
Has the content been updated?
For older versions of the URL, the applet will launch.
"Https://cjrtnc.leaningtech.com/20200206/loader.js"

"shi-Painter" Java applet here.
https://hp.vector.co.jp/authors/VA016309/spainter/

"shi-Painter" is an Applet that is still used all over the world.
I would appreciate it if you could respond.

**Comment by marsicplusplus** [comment]
Hi @satopian,

Using "latest" is not safe as it can serve a mix of what you, the CDN and the browser have cached to that address.
Please use the official releases of the runtime (like the 20200206 that you linked or the latest release version 2.2).

As a matter of fact, starting from the last release, the latest endpoint won't be update anymore.

I've tested the applet with the latest release https://cjrtnc.leaningtech.com/2.2/loader.js and everything seems to be working.
