### ISSUE TITLE
Doesn't work on the Wayback Machine?

### ISSUE THREAD

**Issue by Ecdldaiiere** [leaningtech/cheerpj-appletrunner#48]
Works like a charm, except for on the Wayback Machine. Been trying to run some Java Applets but they are gone from the web and only preserved on the Wayback Machine, but it never loads on there. Example game I'm trying to run https://web.archive.org/web/20061113054646/http://www.eyeone.com/e1gc_no/fr/main/games/cubes/game_play.jsp or https://web.archive.org/web/20080330023406/http://www.eyeone.com/games/cubes.jsp Does this extension not support working on the Wayback Machine?

**Comment by sere** [comment]
Hello Ecdldaiiere,

Please note that using Java applets from the Wayback Machine is, in general, unsupported, since the site add various CSP headers which do not work well with our runtime generated JavaScript code. It's unclear if we can fix the problem, but it's in our list.
