### ISSUE TITLE
Running on a Netgear GS108Tv2

### ISSUE THREAD

**Issue by Gomp5** [leaningtech/cheerpj-appletrunner#52]
Hi, I am running Cheerpj via Chrome on a Netgear GS108Tv2 managed switch but only the menu items show not the switch display. Can someone helpe me for the switch display to show ?

**Comment by marsicplusplus** [comment]
Hi @Gomp5,

We can only offer support for applets that are freely accessible on the public internet and without credentials.

If you are interested in our services, please contact us at appletrunner.business@leaningtech.com.

best wishes,

Lorenzo
