### ISSUE TITLE
LWJGL support soon?

### ISSUE THREAD

**Issue by xX420MCplayerXx** [leaningtech/cheerpj-appletrunner#59]
Hi! I have a question. Will this plugin soon support Java Applets that use LWJGL (Light Weight Java Game Library)? I would love to play MineCraft as it was intended to be played back in 2009, however, this plugin doesn't have LWJGL support. Will it soon be implimented?

**Comment by alexp-sssup** [comment]
There is no current plan to support LWJGL. The fundamental problem is that LWJGL is not actually Java, but a wrapper for a native binary library that cannot be executed in the browser natively.

CheerpJ (and the Applet Runner extensions) are designed to run Java applications and applets. Java code that uses native library cannot be supported out-of-the-box.

**Comment by xX420MCplayerXx** [comment]
Could there be an LWJGL emulation that is toggleable in settings instead?

**Comment by alexp-sssup** [comment]
We don't plan to invest in supporting specific native libraries, our focus is on running pure Java applications and applets. I am sorry we cannot provide a solution for your use case right now.
