### ISSUE TITLE
CheerpJ does not work on my page.

### ISSUE THREAD

**Issue by Photas11** [leaningtech/cheerpj-appletrunner#6]
So today I wanted to log in into our reservation system. But since the logging page is made of applet I can not run it in my browser, so I wanted to try your extension into Chrome, but it seems it doesnt work either.

The page is: http://84.42.243.114/ 

Btw. sorry for my English and thank you for your response.

**Comment by Alexey-Akishin** [comment]
What does not work exactly? [Login form appears successfully](http://dragon.studio/2018/05/cheerpj-issue-6-login-form.png) with current version of CheerpJ.

**Comment by Photas11** [comment]
Yes, it works on login page, but right after I log in, another page shows
up and there is also java applet and when I press "Run Applets", the page
reloads and system log me out. Is there any workaround? I know, it is not
CheerpJ problem.

**Comment by alexp-sssup** [comment]
@Alexey-Akishin Could you try again with version 3.6 or better of CheerpJ Applet Runner?

**Comment by alexp-sssup** [comment]
We have no way to test the website after the login as we do not have credentials. Closing this bug.
