### ISSUE TITLE
Bug report for: http://127.0.0.1:5500/java_practice_12/Java_Theory/myapplet.html

### ISSUE THREAD

**Issue by sandipanrakshit34** [leaningtech/cheerpj-appletrunner#69]

**Comment by alexp-sssup** [comment]
Thank you for reporting this bug, unfortunately this is a localhost URL that we cannot access. Can you give us more information about what is not working for you or attach the applet and HTML page here?

**Comment by alexp-sssup** [comment]
Closing due to lack of information
