### ISSUE TITLE
Bug report for: https://172.125.65.6:8820/forms/frmservlet

### ISSUE THREAD

**Issue by engwisam2022** [leaningtech/cheerpj-appletrunner#70]

**Comment by alexp-sssup** [comment]
Can you clarify what the problem is? CheerpJ Applet Runner is known to work very well with Oracle Forms and Oracle EBS

**Comment by alexp-sssup** [comment]
We just released version 2024.11 with fixes for multiple problems, including one that we think was affecting many Oracle Forms and EBS instances. Let us know if the original problem is not yet fixed for you.
