### ISSUE TITLE
extension not working in https://www.cut-the-knot.org/

### ISSUE THREAD

**Issue by ducaale** [leaningtech/cheerpj-appletrunner#8]
for example https://www.cut-the-knot.org/Curriculum/Arithmetic/ArithmeticSequence.shtml has applet with this applet tag

```<applet code="ArithmeticSequence" width="600" height="300" codebase="/classes" archive="CTKUtility.zip,ArithmeticSequence.zip"></applet>```

and is making this error: ```java.lang.ClassNotFoundException: ArithmeticSequence```

ArithmeticSequence.class can be found inside  https://www.cut-the-knot.org/classes/ArithmeticSequence.zip but this extension is looking at https://www.cut-the-knot.org/classes/ArithmeticSequence.class

**Comment by alexp-sssup** [comment]
This website uses non-standard ZIP files (instead of JARs) to store the classes, and this is not supported by CheerpJ Applet Runner at this time.

**Comment by alexp-sssup** [comment]
This website is now working. Please try CheerpJ Applet Runner version 6.9
